In [12]:
import numpy as np

In [13]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])


In [14]:
print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [15]:
print y 

[[0]
 [1]
 [1]
 [0]]


In [18]:
#Step 2 build model

num_epochs = 60000

#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [19]:
print syn0

[[-0.27389084 -0.82232071  0.16283522 -0.59890891]
 [ 0.99908993  0.00606892 -0.41064962  0.07002389]
 [-0.28158671  0.51369879  0.35599302 -0.26473899]]


In [20]:
print syn1

[[ 0.77518575]
 [-0.69188884]
 [-0.60108857]
 [-0.63001017]]


In [ ]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [26]:
#Step 3 Train Model

for j in xrange(num_epochs):
    #feed forward through layers 0,1, and 2
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    #how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(l2_error)))
    
    #in what direction is the target value?
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    #how much did each l1 value contribute to l2 error
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta= l1_error * nonlin(l1,deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.00244960970043
Error:0.00235116910417
Error:0.00226370906732
Error:0.00218533144568
Error:0.00211456739923
Error:0.00205026020437
